In [2]:
# 1- Create a numpy array of shape (3, 4) and assign 
# random integers between 1 and 10 to every element.
import numpy as np
a_array = np.random.randint(1,10,size=(3,4))
a_array

array([[8, 3, 3, 6],
       [8, 5, 6, 4],
       [1, 3, 2, 6]])

In [36]:
# 2- Find the maximum value in the array created in step 1.

np.max(a_array)

9

In [40]:
# 3- Calculate the mean value of each row in the array.

np.mean(a_array,axis=1,dtype='int32')

array([4, 5, 4], dtype=int32)

In [41]:
# 4- Reshape the array from step 1 into a shape of (2, 6).

np.reshape(a_array,(2,6))

array([[4, 1, 4, 7, 3, 6],
       [3, 9, 1, 9, 3, 4]])

In [42]:
a_array*2

array([[ 8,  2,  8, 14],
       [ 6, 12,  6, 18],
       [ 2, 18,  6,  8]])

In [59]:
# 6- Create a numpy array with values ranging from 0 to 9.
#  Extract the odd numbers from the array.
import numpy as np
b_array = np.arange(10)
oddno = b_array[b_array % 2 !=0]
oddno

array([1, 3, 5, 7, 9])

In [65]:
# 7- Create a 3x3 identity matrix using numpy.

c_array = np.identity(3,dtype='int32')
c_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [76]:
# 8- Create a 5x5 array with random values and normalize it
#  (subtract the mean and divide by the standard deviation of the array).

d_array = np.random.rand(5,5)
d_array
std = np.std(d_array)
mean = np.mean(d_array)
n = (d_array - mean) / std
n

array([[ 0.99911409, -1.6313587 ,  0.18580108, -0.26931775, -1.09519572],
       [-0.89962587,  1.41188821, -1.67452438,  0.32352242,  0.72808246],
       [-1.35439648,  0.18782956,  0.81683693, -0.60406049,  0.70766859],
       [-0.78208725, -1.30324651,  1.29166463,  1.57889551,  0.11174052],
       [ 0.77710567,  0.57399068, -0.9224018 , -0.51895292,  1.3610275 ]])

In [89]:
# 9- Perform element-wise multiplication between two arrays of the same shape.

array1 = np.random.randint(1,10,size =(2,3))
array2 = np.random.randint(1,10,size =(2,3))
array1

array([[9, 8, 4],
       [4, 9, 4]])

In [90]:
array2

array([[6, 7, 3],
       [4, 6, 6]])

In [93]:
array3=array1 * array2


array([[54, 56, 12],
       [16, 54, 24]])

In [ ]:
array3

In [105]:
# 10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).

m_array = np.random.rand(2,2)
m_array

m_array_inch = m_array * 2.54
m_array_inch


array([[1.20822002, 2.16912067],
       [1.68196456, 0.15955555]])

In [3]:
# 11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.

o_array = np.arange(10)
o_array
o_array[o_array%2!=0] = -1
o_array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 12 - Create a 2D array with random values and find the indices of 
# the maximum and minimum values.

k_array = np.random.randint(10,size=(2,2))
k_array

array([[1, 9],
       [8, 3]])

In [9]:
max =  np.unravel_index(np.argmax(k_array), k_array.shape)
print("Maximum value index:", max)

Maximum value index: (0, 1)


Minimum value index: (0, 1)


In [ ]:
min =  np.unravel_index(np.argmin(k_array), k_array.shape)
print("Minimum value index:", min)

In [19]:
import numpy as np
# Create a 2D array with random values
arr = np.random.randn(3, 4)
# Find the indices of the maximum and minimum values
max_index = np.unravel_index(np.argmax(arr), arr.shape) #numpy.unravel_index() function converts a flat index or array of flat indices into a tuple of coordinate arrays.
min_index = np.unravel_index(np.argmin(arr), arr.shape)

print(max_index)
print(arr)
# print("Array:")
# print(arr)
# print("Maximum value index:", max_index)
# print("Minimum value index:", min_index)


(2, 2)
[[-1.12462104 -0.87578927 -1.07279806 -1.14702974]
 [ 0.78220394  0.7320075   1.17119767  0.52260448]
 [ 0.61779605 -2.10253148  2.15744991 -2.02924819]]
