## Python Numpy Tutorial 

In [7]:
import numpy as np

In [12]:

a = [1,2.1,3]
a_array = np.array(a)
a_array.dtype

dtype('float64')

In [13]:
print(a_array)

[1.  2.1 3. ]


In [14]:
a_array.ndim

1

In [17]:
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a_array.shape

(2, 3)

In [22]:
a = [[1,True,3],[4,5,6]]
a_array = np.array(a)
a_array.dtype

dtype('int32')

In [24]:
a_array.shape

(2, 3)

In [33]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array.size
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#access elements in array a_array [r,c]
a_array[2,2]
a_array[2,-1]
a_array[2,:]
a_array[:,1]
a_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [42]:
#assign a value/ change a value
a_array[2,2]=11
a_array
a_array[0:2,1:3]=[[9,10],[8,6]]
a_array

array([[ 1,  9, 10],
       [ 4,  8,  6],
       [ 7,  8, 11]])

In [55]:
a = [[[1,2],[3,4]],[[5,6],[7,8]]]
a_array = np.array(a,dtype='int32')
a_array.shape
a_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
a_array[1,1,0]

7

In [63]:
#initiliaze arrays
a_array=np.zeros(5,dtype='int64')
a_array=np.zeros((2,3),dtype='int32')
a_array=np.ones((2,3),dtype='int32')
a_array=np.full((2,3),10)
a_array=np.full((2,3,4),10,dtype='int32')
a_array

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [64]:
#array of decimal randon values
a_array= np.random.rand(2,3)
a_array

array([[0.52204998, 0.63655264, 0.20102219],
       [0.38585286, 0.93493162, 0.70204709]])

In [68]:
#array of identity matrics
a_array= np.identity(5,dtype='int32')
a_array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [74]:
a_array= np.identity(3,dtype='int32')
a_array1=a_array.copy()
a_array1[0,0]=9

In [76]:
a_array1

array([[9, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
#mathmatics
a_array= np.identity(3,dtype='int32')
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [88]:
a_array+2
a_array*2

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [97]:
a_array1= np.full((2,3),9,dtype='int32')
a_array2= np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)
a_array1*a_array2

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


array([[45, 45, 45],
       [45, 45, 45]])

In [99]:
#trignomatry
a_array= np.identity(3,dtype='int32')
np.cos(a_array)

array([[0.54030231, 1.        , 1.        ],
       [1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 0.54030231]])

In [100]:
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [101]:
#statistics
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.min(a_array)
np.min(a_array,axis=0)
np.min(a_array,axis=1)
np.sum(a_array,axis=1)

array([ 6, 15, 24])

In [119]:
#rearrgrage
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
a_array1= np.full((2,3),9,dtype='int32')
a_array2= np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


In [122]:
#stacking multiple arrays
np.vstack((a_array1,a_array2))
np.hstack((a_array1,a_array2))

array([[9, 9, 9, 5, 5, 5],
       [9, 9, 9, 5, 5, 5]])

In [125]:
#create array from a file
f = np.genfromtxt('readnp.txt',delimiter=',',dtype='int32')
f

array([[ 1,  2,  3, 42, 50],
       [ 4,  5,  6, 60, 42],
       [10,  5,  6,  9, 10],
       [14, 15, 60, 56, 21]])

In [137]:
#advance indexing
f<20
f[f>20]
f[(f>20) | (f<50)]
f[(f>20) & (f<50)]

array([42, 42, 21])

In [136]:
f+2

array([[ 3,  4,  5, 44, 52],
       [ 6,  7,  8, 62, 44],
       [12,  7,  8, 11, 12],
       [16, 17, 62, 58, 23]])