In [12]:
import numpy as np

In [13]:
#array ==> will hold one data type
#list ===> will hold all data type

#numpy array are faster :-
# 1) numpy we cannot append values need to create new array.

a=[1,2,3]
b=[1,2,1.2,3]
a_array = np.array(a)
b_array = np.array(b)
print(a_array.dtype) # check data type
print(b_array.dtype)
print(a_array)
print(b_array)
a_array.ndim # check dimension


int64
float64
[1 2 3]
[1.  2.  1.2 3. ]


1

In [14]:
a_array.ndim  # check dimension

1

In [15]:
a=[[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.dtype
a_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a_array.shape

(2, 3)

In [9]:
a=[[1,2.5,3],[4,5,6]]
a_array = np.array(a)
a_array.dtype

dtype('float64')

In [10]:
a_array

array([[1. , 2.5, 3. ],
       [4. , 5. , 6. ]])

In [17]:
a=[[1,'nidhi',3],[4,5,6]]
a_array = np.array(a)
a_array.dtype
#dtype('<U21')(string)

dtype('<U21')

In [18]:
a_array

array([['1', 'nidhi', '3'],
       ['4', '5', '6']], dtype='<U21')

In [21]:
a_array.shape

(2, 3)

In [22]:
a=[[1,True,3],[4,5,6]]
a_array = np.array(a)
a_array.dtype

dtype('int64')

In [23]:
a

[[1, True, 3], [4, 5, 6]]

In [38]:
a_array.shape

(2, 3)

In [24]:
a=[[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.size
a_array
a_array.ndim

2

In [25]:
#access individual ele in array
#a_array[row][column]
a_array[0][1]

2

In [26]:
a_array[1][2]

6

In [27]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array.size


9

In [28]:
a_array[2][2]

9

In [29]:
a_array.ndim

2

In [30]:
a_array.shape

(3, 3)

In [31]:
a =[[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.size

6

In [32]:
a_array[0][1]

2

In [35]:
a_array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a_array[-1][0]

4

In [36]:
a_array[1:]

array([[4, 5, 6]])

In [37]:
a_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [40]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array.size
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
#changes ele at the index
a_array[2][2]=11
a_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 11]])

In [68]:
a_array[0:2,1:3]=[[9,10],[13,14]]

In [73]:
a=[[[1,2],[4,5]],[[6,7],[8,9]]]
a_array = np.array(a)
a_array.ndim


3

In [75]:
a_array.shape

(2, 2, 2)

In [42]:
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a_array[0][0][0]

IndexError: invalid index to scalar variable.

In [80]:
a_array[1][1][0:]

array([8, 9])

In [44]:
#initialize arrays
a_array = np.zeros(5,dtype='int32')
a_array

array([0, 0, 0, 0, 0], dtype=int32)

In [85]:
a_array = np.zeros((3,2),dtype='int32')
a_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [86]:
a_array = np.ones((3,2),dtype='int32')
a_array

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [88]:
a_array = np.full((3,2),5)
a_array

array([[5, 5],
       [5, 5],
       [5, 5]])

In [89]:
a_array = np.full((3,2),10)
a_array

array([[10, 10],
       [10, 10],
       [10, 10]])

In [93]:
a_array = np.ones((2,3,4),dtype='int32')
a_array

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [94]:
a_array = np.full((2,3,4),10)
a_array

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [45]:
# aarray of decimal values
a_array = np.random.rand(2,3)
a_array

array([[0.90065401, 0.91199135, 0.17937747],
       [0.82654844, 0.7649694 , 0.128261  ]])

In [7]:
#aary of identity matrix
a_aary =np.identity(2,dtype="int32")
a_aary

array([[1, 0],
       [0, 1]], dtype=int32)

In [8]:
type(a_aary)

numpy.ndarray

In [19]:
a_array = np.identity(3,dtype="int32")
a_array1=a_array.copy()
a_array1[0,0]=9

In [20]:
a_array1

array([[9, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [21]:
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [22]:
a_array = np.identity(3,dtype="int32")
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [23]:
a_array+2

array([[3, 2, 2],
       [2, 3, 2],
       [2, 2, 3]], dtype=int32)

In [24]:
a_array*2

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]], dtype=int32)

In [27]:
a_array1 = np.identity(2,dtype='int32')
a_array2 = np.identity(2,dtype='int32')
a_array3 = a_array1 + a_array2
a_array3

array([[2, 0],
       [0, 2]], dtype=int32)

In [35]:
a_array4 = np.full((2,3),9,dtype='int32')
a_array5 = np.full((2,1),5,dtype='int32')
a_array6 = a_array4 + a_array5
a_array6

array([[14, 14, 14],
       [14, 14, 14]], dtype=int32)

In [36]:
#trignometry
a_array = np.identity(3,dtype="int32")
np.cos(a_array)

array([[0.54030231, 1.        , 1.        ],
       [1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 0.54030231]])

In [37]:
#statistics
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.min(a_array)

1

In [41]:
np.max(a_array)

9

In [43]:
#axis=0 (column wise)
np.min(a_array,axis=0)

array([1, 2, 3])

In [44]:
#row wise
np.min(a_array,axis=1)

array([1, 4, 7])

In [45]:
np.sum(a_array)

45

In [46]:
np.sum(a_array,axis=0)

array([12, 15, 18])

In [47]:
np.sum(a_array,axis=1)

array([ 6, 15, 24])

In [52]:
#rearrange
a =[[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
#a_array.reshape(1,9)

In [58]:
a_array.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a_array1 = np.full((2,3),9,dtype='int32')
a_array2 = np.full((2,3),5,dtype='int32')

In [63]:
a_array1

array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)

In [64]:
a_array2

array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [67]:
#vertical stacking
np.vstack((a_array1,a_array2))

array([[9, 9, 9],
       [9, 9, 9],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [71]:
#horizontal stacking
np.hstack((a_array1,a_array2))

array([[9, 9, 9, 5, 5, 5],
       [9, 9, 9, 5, 5, 5]], dtype=int32)

In [74]:
#create array from a file
f = np.genfromtxt('readnp.text',delimiter=',',dtype='int32')
f

array([[ 1,  2,  3, 42, 50],
       [ 4,  5,  6, 60, 42],
       [10,  5,  6,  9, 10],
       [14, 15, 60, 56, 21]], dtype=int32)

In [91]:
#advance indexing
f < 20

False

In [92]:
f>20

False

In [95]:
f[f<20]

TypeError: 'int' object is not subscriptable

In [96]:
f[(f>20) & (f<50)]

TypeError: 'int' object is not subscriptable

In [97]:
f[(f>20) | (f<50)]

TypeError: 'int' object is not subscriptable